# Copyright 2022-Today TechKhedut.
# Part of TechKhedut. See LICENSE file for full copyright and licensing details.
{
    'name': "All in one Insurance Management | All types Insurance Management",
    'version': "3.1.0",
    'description': """All in one Insurance Management""",
    'summary': "Insurance Management",
    'author': 'TechKhedut Inc.',
    'category': 'Industry',
    'website': "https://techkhedut.com",
    'depends': [
        'mail',
        'contacts',
        'base',
        'sale_management',
        'website',
        'portal',
        'crm'
    ],
    'data': [
        # data
        'data/insurance_time_period_data.xml',
        'data/sequence.xml',
        'data/insurance_invoice_data_views.xml',
        'data/claim_document_type_data_views.xml',
        'data/insured_document_type_data_views.xml',
        'data/insurance_category_data_views.xml',
        'data/sub_category_data_views.xml',
        'data/ir_cron.xml',
        'data/insurance_nominee_relation_data.xml',
        'data/claim_reasons_data.xml',
        'data/website_menu.xml',
        # Security
        'security/groups.xml',
        'security/ir.model.access.csv',
        'security/ir_rules.xml',
        # wizards
        'wizards/insurance_claim_views.xml',
        'wizards/renew_insurance_views.xml',
        'wizards/crm_insurance_views.xml',
        'wizards/re_insurance_contract_views.xml',
        'wizards/re_insurance_reject_reason_views.xml',
        'wizards/insurance_expiry_report_views.xml',
        'wizards/insurance_report_views.xml',
        'wizards/claim_report_views.xml',
        'wizards/extend_insurance_views.xml',
        # 'wizards/patient_contract_claim_report,xml',
        # Views
        'views/assets.xml',
        'views/claim_views.xml',
        'views/insurance_views.xml',
        'views/insurance_policy_views.xml',
        'views/insurance_time_period_views.xml',
        'views/insured_document_views.xml',
        'views/claim_document_views.xml',
        'views/claim_document_type_views.xml',
        'views/insured_document_type_views.xml',
        'views/invoice_inherit_views.xml',
        'views/res_partner_inherit_views.xml',
        'views/insurance_sub_category_views.xml',
        'views/insurance_category_views.xml',
        'views/insurance_nominee_views.xml',
        'views/insurance_buying_for_views.xml',
        'views/claim_reasons_views.xml',
        'views/insured_details_views.xml',
        'views/res_config_setting_view.xml',
        'views/crm_lead_inherit_views.xml',
        'views/res_company_inherit_views.xml',
        'views/re_insurance_views.xml',
        'views/re_insurance_type_views.xml',
        # Web Template
        'views/templates/web_template_views.xml',
        # report
        'report/insurance_report.xml',
        'report/insurance_claim_report.xml',
        'report/vehicle_insurance_report.xml',
        # 'report/provider_service_report.xml',  # requires OCA report_xlsx (not available on Odoo SaaS)
        # 'report/patient_claim_contract.xml',
        # data
        'data/insurance_expired_mail.xml',
        'data/claim_approved_mail.xml',
        'data/insurance_policy_cancellation_mail.xml',
        'data/upcoming_installment_mail.xml',
        'data/quote_ref_number_mail_template.xml',
        'data/reinsurance_details_submission_mail.xml',
        # Menus
        'views/menus.xml',
    ],
    'assets': {
        'web.assets_frontend': [
            'tk_insurance_management/static/src/css/theme.css',
            'tk_insurance_management/static/src/js/other/script.js',
        ],
        'web.assets_backend': [
            'tk_insurance_management/static/src/xml/template.xml',
            'tk_insurance_management/static/src/scss/style.scss',
            'tk_insurance_management/static/src/js/lib/apexcharts.js',
            'tk_insurance_management/static/src/js/dashboard/insurance_dashboard.js',
        ],
    },
    'images': ['static/description/banner.gif'],
    'installable': True,
    'application': True,
    'auto_install': False,
    'license': 'OPL-1',
    'price': 99,
    'currency': 'USD'
}
